test vendor rebuild

diff --git a/.github/workflows/ODBC.yml b/.github/workflows/ODBC.yml
--- a/.github/workflows/ODBC.yml
+++ b/.github/workflows/ODBC.yml
@@ -29,6 +29,15 @@ jobs:
           fetch-depth: 0
           ref: ${{ inputs.git_ref }}
 
+      - name: Check first line of duckdb.h
+        run: |
+          first_line=$(head -n 1 src/duckdb/src/include/duckdb.h)
+          if [[ "$first_line" == *"WRONG"* ]]; then
+            echo "Error: The wrong commit has been checked out!"
+            exit 1
+          fi
+          echo "First line of duckdb.h: $first_line"
+
       - uses: ./.github/actions/manylinux_2014_setup
         with:
           ninja-build: 1
